version: "3"
services:
  db:
    container_name: customers_db
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 2

  server:
    container_name: customers_node
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
